# Inventory = danh sách máy chủ Ansible sẽ quản lý
# Ở đây ta chạy trên chính máy local (WSL2 Ubuntu)
[local]
localhost ansible_connection=local
# ansible_connection=local → không cần SSH, chạy trực tiếp
